rvm:
- 2.0
- 2.5
- 2.6
- 2.7
- 3.0
- ruby-head
- ruby-head-clang
- jruby-9.1
- jruby-head
script: bundle exec rake spec
env:
  global:
    secure: Xt9aOp3jO9r7e+ljIRJSIZwifiYXzirp0wZ3GbsQ8zOd5vmIjIehReu+7e4fRm1/Wfp8q85Yl5otYPxa2HOeDl67aA9WIiCvSH8cSb4QrM6jahAc9T2td5io9GSiWPWaQiA3Th8dOOuPmBaiLWgBZ9k9MzMMJ5lj1F1whW6gTEE=
